version: "3.8"

services:
  mongo:
    image: mongo:4.4
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: qwerty
    volumes:
      - "C:/Users/alkam/Desktop/Documents/MegaEdgeConversions/data:/data/db"
    networks:
      - mongo-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: qwerty
      ME_CONFIG_MONGODB_URL: mongodb://admin:qwerty@mongo:27017/
    depends_on:
      - mongo
    networks:
      - mongo-network

  nodeapp:
    build: .
    container_name: node-server
    ports:
      - "5050:5050"
    depends_on:
      - mongo
    networks:
      - mongo-network

networks:
  mongo-network:
